### ISSUE TITLE
NosflareDeploy is not yet compatible with version 1.15.9

### ISSUE THREAD

**Issue by pcwd** [PastaGringo/NosflareDeploy#1]
-------------------------- NosflareDeploy v1.0 ---------------------------
    _   __           ______                ____             __
   / | / /___  _____/ __/ /___  ____ ___  / __ \___  ____  / /___  __  __
  /  |/ / __ \/ ___/ /_/ / __ \/ __// _ \/ / / / _ \/ __ \/ / __ \/ / / /
 / /|  / /_/ (__  ) __/ / /_/ / /  /  __/ /_/ /  __/ /_/ / / /_/ / /_/ /
/_/ |_/\____/____/_/ /_/\__,_/_/   \___/_____/\___/ .___/_/\____/\__, /
                                                 /_/            /____/.sh
-------------------------- NosflareDeploy v1.0 ---------------------------
                                                                2024-04-21

Latest Nosflare (https://github.com/spl0itable/nosflare) version available: 1.15.9

NosflareDeploy is not yet compatible with version 1.15.9 (currently: 1.13.9)
Please open an Github issue to ask an update: https://github.com/PastaGringo/NosflareDeploy/issues/new

**Comment by PastaGringo** [comment]
Hi,

Should be OK! Please try and let me now ;)
