### ISSUE TITLE
❌ Cannot get the KV namespace ID

### ISSUE THREAD

**Issue by pcwd** [PastaGringo/NosflareDeploy#2]
Verifying who you are ...

 ⛅️ wrangler 3.39.0
-------------------
Getting User settings...
👋 You are logged in with an API Token, associated with the email Satoshi.Nakamoto@nostr.love!
┌─────────────────────────────────────┬──────────────────────────────────┐
│ Account Name                        │ Account ID                       │
├─────────────────────────────────────┼──────────────────────────────────┤
│ HIDDEN                              │ HIDDEN                           │
└─────────────────────────────────────┴──────────────────────────────────┘
🔓 To see token permissions visit https://dash.cloudflare.com/profile/api-tokens

Verify if wrangler.toml (/home/admin/nosflare/wrangler.toml) exists ...
Wrangler.toml exists ✅

Checking existing KV(s) from your Cloudflare account ...
Found 1 KV(s) ✅

Looking for the KV-ID for KV with title nosflare-kvdb ...
❌ Cannot get the KV namespace ID
Please, run the script one more time in case of Cloudflare timeout (good excuse, chief).
If still not working, open a github issue!

**Comment by PastaGringo** [comment]
Hi,

Can you please set the debug var to 1: `debug=1` and paste here the block where `[DEBUG]` is specified ?
Thanks

**Comment by pcwd** [comment]
Here ya go...

Looking for the KV-ID for KV with title nosflare-kvdb ...
[DEBUG] Listing KV namespace:
JSON:
[
  {
    "id": "ec0c97fa26e5495dbacb039e622381e3",
    "title": "worker-kvdb",
    "supports_url_encoding": true
  }
]
[
  {
    "id": "ec0c97fa26e5495dbacb039e622381e3",
    "title": "worker-kvdb",
    "supports_url_encoding": true
  }
]
[DEBUG]  ->
[DEBUG] End, Bye.

**Comment by PastaGringo** [comment]
Thanks.

I updated the code. Can you `git pull` (or download the file directly) and try again please?
Thanks

**Comment by pcwd** [comment]
All fixed. Tks.
